SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
MAX_ASTEROID_SPAWN = 40
TRANSFORMING_ASTEROID_RADIUS = 80
TRANSFORMING_ASTEROID_HEALTH = 10

SHIP_RADIUS = 20
SHIP_TURN_SPEED = 300
SHIP_SPEED = 200

SHIP_SHOOT_COOLDOWN = 0.3  # seconds
SHIP_SHOOT_SPEED = 500

SHOT_RADIUS = 5

ACCELERATION = 1
ACCELERATION_FRICTION = 0.2